In [ ]:
import tensorflow as tf
from tensorflow.lite.python.util import convert_bytes_to_c_source
from PIL import Image, ImageFilter
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical

In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
train16 = []
flat = []

In [ ]:
for images in x_train:
  temp = Image.fromarray(images)
  temp = temp.resize((16,16))
  temp = np.array(temp)
  flat.append(temp)
  temp = temp.flatten()
  train16.append(temp)

test16 = np.array(train16)
flat = np.array(flat)
# image = x_train[0]
# img = Image.fromarray(image)
# display(img)
# print(img.size)
# img = img.resize((16,16))
# print(img.size)
# display(img)

In [ ]:
test16 = []

for images in x_test:
  temp = Image.fromarray(images)
  temp = temp.resize((16,16))
  temp = np.array(temp)
  temp = temp.flatten()
  test16.append(temp)

test16 = np.array(test16)

In [ ]:
index = 85
print(repr(train16[index]))
img = Image.fromarray(flat[index])
display(img)

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  14,  55, 105,
       112,   0,   0,   0,   0,   0,   0,   0,   0,   0,  33,  80, 150,
       205, 228, 227, 144,   0,   0,   0,   0,   0,   0,   2,  56, 190,
       224, 229, 112,  58,  51,  29,   0,   0,   0,   0,   0,   0,   0,
        77, 244, 215,  87,  25,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  54, 216, 236,  74,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  20, 192, 130,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  72,  56,   0,  13, 215,  85,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 124, 22

In [ ]:
lol = train16
print(type(train16))
train16 = np.array(train16)
print(type(train16))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
temp = []
for i in range(len(y_train)):
    temp.append(to_categorical(y_train[i], num_classes=10))

y_train = np.array(temp)

In [ ]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
# print(lol[0][0])
# a = lol[0][0]
# l = f'{a:08b}'
# print(l)

for idx,num in enumerate(lol[0]):
  l = f'{num:08b}'
  print(l)




In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(10, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(20, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.relu))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [ ]:
model.fit(train16, y_train, epochs=60)

In [ ]:
index = 0
# test = np.array([test16[index]])

img = Image.fromarray(x_test[index])
display(img)
 
# model.predict(test)

In [ ]:
model.save("model_digit16bit")

INFO:tensorflow:Assets written to: model_digit16bit/assets


In [ ]:
!zip -r /content/model.zip /content/model_digit16bit

  adding: content/model_digit16bit/ (stored 0%)
  adding: content/model_digit16bit/assets/ (stored 0%)
  adding: content/model_digit16bit/variables/ (stored 0%)
  adding: content/model_digit16bit/variables/variables.index (deflated 63%)
  adding: content/model_digit16bit/variables/variables.data-00000-of-00001 (deflated 19%)
  adding: content/model_digit16bit/keras_metadata.pb (deflated 86%)
  adding: content/model_digit16bit/saved_model.pb (deflated 88%)


In [ ]:
np.savetxt('mnist.csv', x_train[0], fmt='%d', delimiter=',')

In [ ]:


# for i in range (10):
#   plt.imshow(x_train[i],cmap=plt.cm.binary)
#   plt.show()

# print(x_test[0])


In [ ]:
x_train = tf.keras.utils.normalize(x_train, axis=1)
x_test = tf.keras.utils.normalize(x_test, axis=1)
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
# model.add(tf.keras.layers.Dense(10, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(20, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=3)

In [ ]:
model.summary()

val_loss, val_acc = model.evaluate(x_test, y_test)
print(val_loss)
print(val_acc)

In [ ]:
predictions = model.predict(x_test)
print(predictions)

In [ ]:
test_var = 13

print(np.argmax(predictions[test_var]))
np.savetxt('xtest.csv', x_test[test_var], delimiter=',')

plt.imshow(x_test[test_var],cmap=plt.cm.binary)
plt.show()

In [ ]:
model.save('20-10.h5')

In [ ]:
for layerNum, layer in enumerate(model.layers):
    weights = layer.get_weights()[0]
    biases = layer.get_weights()[1]

    for toNeuronNum, bias in enumerate(biases):
        print(f'{layerNum}B -> L{layerNum+1}N{toNeuronNum}: {bias}')

    for fromNeuronNum, wgt in enumerate(weights):
        for toNeuronNum, wgt2 in enumerate(wgt):
            print(f'L{layerNum}N{fromNeuronNum} \
                  -> L{layerNum+1}N{toNeuronNum} = {wgt2}')


In [ ]:
tflname = "tf_lite_model.tflite"
tf_lite_converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = tf_lite_converter.convert()
open(name, "wb").write(tflite_model)
convert_bytes(get_file_size(TF_LITE_MODEL_FILE_NAME), "KB")

In [ ]:
# def imageprepare(argv):
#     """
#     This function returns the pixel values.
#     The imput is a png file location.
#     """
#     im = Image.open(argv).convert('L')
#     width = float(im.size[0])
#     height = float(im.size[1])
#     newImage = Image.new('L', (28, 28), (255))  # creates white canvas of 28x28 pixels

#     if width > height:  # check which dimension is bigger
#         # Width is bigger. Width becomes 20 pixels.
#         nheight = int(round((20.0 / width * height), 0))  # resize height according to ratio width
#         if (nheight == 0):  # rare case but minimum is 1 pixel
#             nheight = 1
#             # resize and sharpen
#         img = im.resize((20, nheight), Image.ANTIALIAS).filter(ImageFilter.SHARPEN)
#         wtop = int(round(((28 - nheight) / 2), 0))  # calculate horizontal position
#         newImage.paste(img, (4, wtop))  # paste resized image on white canvas
#     else:
#         # Height is bigger. Heigth becomes 20 pixels.
#         nwidth = int(round((20.0 / height * width), 0))  # resize width according to ratio height
#         if (nwidth == 0):  # rare case but minimum is 1 pixel
#             nwidth = 1
#             # resize and sharpen
#         img = im.resize((nwidth, 20), Image.ANTIALIAS).filter(ImageFilter.SHARPEN)
#         wleft = int(round(((28 - nwidth) / 2), 0))  # caculate vertical pozition
#         newImage.paste(img, (wleft, 4))  # paste resized image on white canvas

#     # newImage.save("sample.png

#     tv = list(newImage.getdata())  # get pixel values

#     # normalize pixels to 0 and 1. 0 is pure white, 1 is pure black.
#     tva = [(255 - x) * 1.0 / 255.0 for x in tv]
#     print(tva)
#     return tva

In [ ]:
# print(imageprepare('./2-000.png'))

In [ ]:
# converter = tf.lite.TFLiteConverter.from_keras_model(model)
# converter.optimizations = [tf.lite.Optimize.DEFAULT]
# tflite_model = converter.convert()

# with open('model.tflite', 'wb') as f:
#   f.write(tflite_model)

In [ ]:
# source_text, header_text = convert_bytes_to_c_source(tflite_model,  "model")

# with  open('model.h',  'w')  as  file:
#     file.write(header_text)

# with  open('model.cc',  'w')  as  file:
#     file.write(source_text)

In [ ]:
# tflmodel = tf.lite.Interpreter('model.tflite')

# tflmodel_predictions = []

# tflmodel.allocate_tensors()

# tflmodel_input_index = tflmodel.get_input_details()[0]["index"]
# tflmodel_output_index = tflmodel.get_output_details()[0]["index"]
# print(tflmodel_input_index)
# print(tflmodel_input_index)

# for x_value in x_test:
#     x_value_tensor = tf.convert_to_tensor([[x_value]], dtype=np.float32)
#     tflmodel.set_tensor(0, x_value_tensor)
#     tflmodel.invoke()
#     tflmodel_predictions.append(tflmodel.get_tensor(tflmodel_output_index)[0])

# plt.clf()
# plt.title('Comparison of various models against actual values')
# plt.plot(x_test, y_test, 'bo', label='Actual')
# plt.plot(x_test, predictions, 'ro', label='Original predictions')
# plt.plot(x_test, tflmodel_predictions, 'bx', label='Lite predictions')
# plt.legend()
# plt.show()
    